grasp01_arm:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin #kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.1
  kinematics_solver_timeout: 5.0
  kinematics_solver_attempts: 3